/*
 * Tarea PROG10: Reconstrucción de la aplicación incorporando la capa gráfica.
 */
package basicos;

import javax.swing.JOptionPane;

/**
 * Clase para gestión gráfica de boletines de noticias entre los trabajadores.
 *
 * @since version 2.0 13/04/2014 (Tarea PROG10)
 * @author RociodeMula <rociodemula@gmail.com>
 * @version 2.0 13/04/2014 (Tarea PROG10)
 */
public class BoletinNoticiasUI extends javax.swing.JDialog {

    /**
     * Constructor de la clase BoletinNoticiasUI. Permite la creación de ventana
     * para el envio de boletines de correo al personal.
     *
     * @since version 2.0 13/04/2014
     * @param parent frame desde donde se abre el form.
     * @param modal que se establece a true o false
     */
    public BoletinNoticiasUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        valorTexto = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valorClave = new javax.swing.JPasswordField();
        valorAsunto = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        valorUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Envío de boletín de noticias por e-mail a los trabajadores.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Asunto:");

        jLabel2.setText("Texto del mensaje (admite etiquetas html):");

        valorTexto.setColumns(20);
        valorTexto.setRows(5);
        jScrollPane1.setViewportView(valorTexto);

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        valorUsuario.setText("empresa@gmail.com");
        valorUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(valorAsunto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(valorClave, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                    .addComponent(valorUsuario))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 56, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar)
                .addGap(18, 18, 18)
                .addComponent(botonCancelar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valorAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valorClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.setVisible(false); // ocultamos la ventana
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String email = valorUsuario.getText(); //String para guardar el mail
        boolean exito;
        int contadorExitos = 0, contadorErrores = 0;
        if (!(email.isEmpty() || valorClave.getPassword().toString().isEmpty()
                || valorAsunto.getText().isEmpty() || valorTexto.getText().isEmpty())) {
            // si todos los campos están rellenos, pasamos a comprobar si el mail es de la empresa
            if (email.endsWith("@gmail.com")) {
                try {
                    Validar.esEmailCorrecto(email); //validamos si el mail es correcto.
                    Auxiliar.leerFichero();
                    int proporcion = 100 / Auxiliar.archivo.size();
                    int progreso = 0;
                    for (Trabajador trabajador : Auxiliar.archivo) {
                        //mandaremos el boletín a cada elemento en e archivo de trabajadores.
                        char[] clave = valorClave.getPassword();
                        String stringClave = new String(clave);
                        //for (char letra : clave){
                        //    stringClave = stringClave + letra;
                        //}
                        exito = trabajador.enviarEmail(email,
                                stringClave,
                                valorAsunto.getText(), valorTexto.getText());
                        //el método enviarEmail() se encargaria del lanzamiento de correo
                        //propiamente dicho, ya sea interno, o externo.
                        if (exito) {
                            contadorExitos++;
                        } else {
                            contadorErrores++;
                        }
                    }
                    JOptionPane.showMessageDialog(null, "Total email enviados: " + contadorExitos
                            + "\nTotal email fallidos: " + contadorErrores, "Resultado mailing",
                            JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false); //ocultamos la ventana
                } catch (Exception ex) {
                    //en caso de que haya algún problema con la validación, saltará 
                    //la excepción.
                    JOptionPane.showMessageDialog(null, ex.getMessage()
                            + ". Disculpe las molestias.", "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                //en caso de que el mail no pase el filtro de la empresa, lanzamos
                //el mensaje de error.
                JOptionPane.showMessageDialog(null, "El usuario no pertenece a la empresa"
                        + ". Comprúebelo y tecléelo de nuevo.", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            //en caso de que falten datos por rellenar, lanzamos el error
            JOptionPane.showMessageDialog(null, "Faltan datos"
                    + ". Compruébelo e inténtelo de nuevo.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void valorUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorUsuarioActionPerformed

    /* Comentamos el método main para evitar confusiones
     * 
     * @param args the command line arguments
     *//*
     public static void main(String args[]) {
     /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     *//*
     try {
     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
     if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
     }
     }
     } catch (ClassNotFoundException ex) {
     java.util.logging.Logger.getLogger(BoletinNoticiasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
     java.util.logging.Logger.getLogger(BoletinNoticiasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
     java.util.logging.Logger.getLogger(BoletinNoticiasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     java.util.logging.Logger.getLogger(BoletinNoticiasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
     //</editor-fold>

     /* Create and display the dialog *//*
     java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     BoletinNoticiasUI dialog = new BoletinNoticiasUI(new javax.swing.JFrame(), true);
     dialog.addWindowListener(new java.awt.event.WindowAdapter() {
     @Override
     public void windowClosing(java.awt.event.WindowEvent e) {
     System.exit(0);
     }
     });
     dialog.setVisible(true);
     }
     });
     }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField valorAsunto;
    private javax.swing.JPasswordField valorClave;
    private javax.swing.JTextArea valorTexto;
    private javax.swing.JTextField valorUsuario;
    // End of variables declaration//GEN-END:variables
}
