/*
 * Tarea PROG10: Reconstrucción de la aplicación incorporando la capa gráfica.
 */
package basicos;

import javax.swing.JOptionPane;

/**
 * Clase para gestión gráfica de creación de trabajadores eventuales.
 *
 * @since version 2.0 13/04/2014 (PROG10)
 * @author RociodeMula <rociodemula@gmail.com>
 * @version 2.0 13/04/2014 (PROG10)
 */
public class CrearTrabajadorEventualUI extends javax.swing.JDialog {

    //declaramos e inicializamos las variables estáticas
    static TrabajadorEventual trabajador = null;
    static CuentaBancaria ccc = null;

    /**
     * Constructor de laclase CrearTrabajadorEventualUI
     * 
     * @since version 2.0 13/04/2014
     * @param parent frame desde donde se crea el objeto
     * @param modal modo de arranque (true o false)
     */
    public CrearTrabajadorEventualUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonGrabar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        valorContrato = new javax.swing.JTextField();
        valorNacimiento = new javax.swing.JTextField();
        valorNif = new javax.swing.JTextField();
        valorNombre = new javax.swing.JTextField();
        valorAltura = new javax.swing.JTextField();
        valorOcupacion = new javax.swing.JTextField();
        valorEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        valorHijos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        valorCcc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        valorTelefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        valorColaboraciones = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        valorHoras = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Trabajador Eventual"));

        jLabel1.setText("NIF/NIE:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Fecha de nacimiento:");

        jLabel4.setText("Altura:");

        jLabel5.setText("Ocupación:");

        jLabel6.setText("Fecha de contratación:");

        botonGrabar.setText("Grabar");
        botonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGrabarActionPerformed(evt);
            }
        });

        jLabel7.setText("e-mail:");

        valorNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorNombreKeyTyped(evt);
            }
        });

        valorOcupacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorOcupacionKeyTyped(evt);
            }
        });

        valorEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorEmailKeyTyped(evt);
            }
        });

        jLabel8.setText("Nº de hijos:");

        valorHijos.setText("0");
        valorHijos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorHijosKeyTyped(evt);
            }
        });

        jLabel9.setText("Nº cuenta:");

        jLabel10.setText("(Formato 20 dígitos sin guiones)");

        jLabel11.setText("Teléfono:");

        jLabel12.setText("Nº de Colaboraciones:");

        valorColaboraciones.setText("0");
        valorColaboraciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorColaboracionesKeyTyped(evt);
            }
        });

        jLabel13.setText("Nº de horas:");

        valorHoras.setText("8");
        valorHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorHorasKeyTyped(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonGrabar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonCancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(71, 71, 71)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(1, 1, 1)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(valorNif, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valorAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valorOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10)
                                                .addGap(11, 11, 11))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(valorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(valorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(valorNombre)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(valorHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(valorNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(valorCcc))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(valorContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(valorColaboraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(valorHoras)))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(valorNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(valorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(valorHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valorNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(valorCcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valorAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(valorOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(valorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(valorContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(valorColaboraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(valorHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGrabar)
                    .addComponent(botonCancelar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGrabarActionPerformed
        try {
            // comprobamos que el NIF/NIE no exista ya en el archivo
            if (GMainUI.buscarTrabajador(valorNif.getText(), false) != null) {
                // si devuelve algo que no sea -1 es que ese nif/nie ya existe.
                throw new Exception("El NIF/NIE ya existe");
            } //si no existe, cargamos los objetos a incluir en elarchivo en las
              //variables estáticas
            ccc = new CuentaBancaria(valorCcc.getText(), valorNif.getText(),
                    valorNombre.getText());
            trabajador = new TrabajadorEventual(valorNombre.getText(), valorNif.getText(),
                    valorNacimiento.getText(), valorAltura.getText(), valorOcupacion.getText(),
                    valorTelefono.getText(), valorHijos.getText(), ccc, valorContrato.getText(),
                    valorEmail.getText(), valorColaboraciones.getText(), valorHoras.getText());
            //devolvemos el control a GmainUI
            this.setVisible(false);
            //lanzamos un mensaje informativo de que se ha creado un trabajador nuevo 
            //(aunque todavía no está incluido en el archivo)
            JOptionPane.showMessageDialog(null, "Se ha creado un trabajador eventual.", "Atención",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            // si se ha recogido alguna excepción, lanzamos el mensaje documental.
            JOptionPane.showMessageDialog(null, ex.getMessage()
                    + ". Comprúebelo y tecléelo de nuevo.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonGrabarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        trabajador = null; //borramos la variable puente.
        this.setVisible(false); //si se pulsa cancelar, volvemos a GMainUI
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void valorEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorEmailKeyTyped
        if (valorEmail.getText().length()>45){
            JOptionPane.showMessageDialog(null, "Este dato tiene un límite de 45 caracteres."
                    + "\nDisculpe las molestias.", "Error", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_valorEmailKeyTyped

    private void valorNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorNombreKeyTyped
        if (valorNombre.getText().length()>45){
            JOptionPane.showMessageDialog(null, "Este dato tiene un límite de 45 caracteres."
                    + "\nDisculpe las molestias.", "Error", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_valorNombreKeyTyped

    private void valorOcupacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorOcupacionKeyTyped
        if (valorOcupacion.getText().length()>20){
            JOptionPane.showMessageDialog(null, "Este dato tiene un límite de 20 caracteres."
                    + "\nDisculpe las molestias.", "Error", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_valorOcupacionKeyTyped

    private void valorHijosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorHijosKeyTyped
        if (valorHijos.getText().length()>6){
            JOptionPane.showMessageDialog(null, "Este dato tiene un límite de 6 cifras."
                    + "\nDisculpe las molestias.", "Error", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_valorHijosKeyTyped

    private void valorColaboracionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorColaboracionesKeyTyped
        if (valorColaboraciones.getText().length()>3){
            JOptionPane.showMessageDialog(null, "Este dato tiene un límite de 3 cifras."
                    + "\nDisculpe las molestias.", "Error", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_valorColaboracionesKeyTyped

    private void valorHorasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorHorasKeyTyped
        if (valorHoras.getText().length()>3){
            JOptionPane.showMessageDialog(null, "Este dato tiene un límite de 3 cifras."
                    + "\nDisculpe las molestias.", "Error", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_valorHorasKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        trabajador = null; //borramos la variable puente.
        this.setVisible(false); //si se pulsa cancelar, volvemos a GMainUI
    }//GEN-LAST:event_formWindowClosing
    
    /**
     * Método que devuelve el trabajador instanciado en la ventana. En caso de 
     * que se haya pulsado el botón Cancelar o cerrado la ventana, su valor
     * será null.
     * 
     * @since version 2.0 13/04/2014
     * @return TrabajadorEventual instanciado con los datos tecleados en la ventana.
     */
    public TrabajadorEventual getTrabajador() {
        return trabajador;
    }

    /* Se comenta el método main() y de deshabilita del javadoc.
     * @param args the command line arguments
     */ /*
     public static void main(String args[]) {
     /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */ /*

    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    }
    catch (ClassNotFoundException ex

    
        ) {
            java.util.logging.Logger.getLogger(MostrarTrabajadorFijoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex

    
        ) {
            java.util.logging.Logger.getLogger(MostrarTrabajadorFijoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex

    
        ) {
            java.util.logging.Logger.getLogger(MostrarTrabajadorFijoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex

    
        ) {
            java.util.logging.Logger.getLogger(MostrarTrabajadorFijoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the dialog *//*
     java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     MostrarTrabajadorFijoUI dialog = new MostrarTrabajadorFijoUI(new javax.swing.JFrame(), true);
     dialog.addWindowListener(new java.awt.event.WindowAdapter() {
     @Override
     public void windowClosing(java.awt.event.WindowEvent e) {
     System.exit(0);
     }
     });
     dialog.setVisible(true);
     }
     });
     } */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField valorAltura;
    private javax.swing.JTextField valorCcc;
    private javax.swing.JTextField valorColaboraciones;
    private javax.swing.JTextField valorContrato;
    private javax.swing.JTextField valorEmail;
    private javax.swing.JTextField valorHijos;
    private javax.swing.JTextField valorHoras;
    private javax.swing.JTextField valorNacimiento;
    private javax.swing.JTextField valorNif;
    private javax.swing.JTextField valorNombre;
    private javax.swing.JTextField valorOcupacion;
    private javax.swing.JTextField valorTelefono;
    // End of variables declaration//GEN-END:variables
}
